// <auto-generated />
using System;
using CMPS.ProjectManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMPS.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    partial class ProjectManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMPS.ProjectManagement.Domain.Aggregates.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("CMPS.ProjectManagement.Domain.Aggregates.Project", b =>
                {
                    b.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.DateRange", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsMany("CMPS.ProjectManagement.Domain.Entities.Task", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("AssignedToUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("Tasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.DateRange", "Schedule", b2 =>
                                {
                                    b2.Property<Guid>("TaskId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("EndDate")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("EndDate");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("StartDate");

                                    b2.HasKey("TaskId");

                                    b2.ToTable("Tasks");

                                    b2.WithOwner()
                                        .HasForeignKey("TaskId");
                                });

                            b1.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.TaskDescription", "Description", b2 =>
                                {
                                    b2.Property<Guid>("TaskId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)")
                                        .HasColumnName("Description");

                                    b2.HasKey("TaskId");

                                    b2.ToTable("Tasks");

                                    b2.WithOwner()
                                        .HasForeignKey("TaskId");
                                });

                            b1.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.TaskName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("TaskId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("nvarchar(250)")
                                        .HasColumnName("Name");

                                    b2.HasKey("TaskId");

                                    b2.ToTable("Tasks");

                                    b2.WithOwner()
                                        .HasForeignKey("TaskId");
                                });

                            b1.Navigation("Description")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Schedule")
                                .IsRequired();
                        });

                    b.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.ProjectCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Code");

                            b1.HasKey("ProjectId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.ProjectDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("Description");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("CMPS.ProjectManagement.Domain.ValueObjects.ProjectName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Name");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
